1.Split this String



In [ ]:
s = "Hi there !!!"

In [2]:
s.split(" ")

['Hi', 'there', 'Sam!']

2.Use .format() to print the following String.

Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "planetX"
diameter = 127434

In [4]:
"The diameter of {} is {} Kilometers".format(planet,diameter)

'The diameter of Earth is 12742 Kilometers'

3.In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

Numpy

In [6]:
import numpy as np

4.1 Create an array of 10 Zeros?

4.2 Create an array of 10 fives?

In [8]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
array = np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5.Create an array of all the even integers from 20 to 40

In [10]:
array = np.arange(20,40,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

6.Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7.Concantenate a and b 

a = np.array([1,2,3]), b = np.array([4,5,6])

In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
gfg = np.concatenate((arr1,arr2))
gfg

array([1, 2, 3, 4, 5, 6])

Pandas

8.Create a daraframe with 3 rows and 2 columns

In [13]:
import pandas as pd

In [14]:
data = [10,20,30]

df = pd.DataFrame(data, columns=['Numbers'])
df

Numbers
0       10
1       20
2       30

9.Generate the series of dates from 1st jan, 2023 to 10th Feb,2023

In [16]:
per1 = pd.date_range(start ='01-01-2023', end = '10-02-2023')
per1

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

10.Create 2D list to DataFrame

lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

In [17]:
lists = [[1,'zzz',22],[2,'yyy',25],[3,'xxx',24]]

In [18]:
df = pd.DataFrame(lists, columns = ['S.no', 'text', 'value'])
df

S.no text  value
0     1  aaa     22
1     2  bbb     25
2     3  ccc     24